### ISSUE TITLE
Alternative text for hosts/urls

### ISSUE THREAD

**Issue by sengaya** [Cyclenerd/static_status#13]
I recently had the need to not expose the hosts/urls that are tested. I implemented an optional "alternative text" that is displayed instead of the host/url when set.

If this is of interest, I can do a PR. It's fully compatible to the existing configuration. If you want to use the alternative text, you append a `|` after the host/url and the text you want to be displayed.

**Comment by Cyclenerd** [comment]
You can also use your `/etc/hosts` file.  That's how I do it:
![Annotation 2020-07-13 102113](https://user-images.githubusercontent.com/176242/87280606-a0f8a180-c4f2-11ea-95b4-222ac599f70a.png)

**Comment by sengaya** [comment]
The `/etc/hosts` approach is pretty nice as it needs no further change in the code. Unfortunately it does not work for my use case for two reasons: I run the script in a docker environment where I cannot change `/etc/hosts` and I want to be able to change the complete text, including e.g. `ping` etc.

I pushed my patch here: https://github.com/sengaya/static_status/commit/a44bc15081d5dbe068c32980530735bcc3d6574e
Needs a bit more testing and probably documentation before I would do a PR. Let me know what you think. Also, totally fine if you do not want to include that patch.

**Comment by Cyclenerd** [comment]
I think it's a good idea. You are welcome to send a PR. Please include documentation and examples if necessary. Please also have everything checked once with https://www.shellcheck.net/. Then I have little to do and everyone quickly get the new cool feature!

**Comment by Cyclenerd** [comment]
Thank you 👍
