### ISSUE TITLE
Issue with alternate text using nc with port specified

### ISSUE THREAD

**Issue by Jakoski360** [Cyclenerd/static_status#15]
I'm attempting to add custom text to the output of the nc command using the pipe which works fine with curl, but with nc the custom text is interpreted as part of the port.

Expected output is the custom text to be shown, instead the custom text is part of the port when it is an unknown port.:
`nc;example.com;25565`
`nc;.example.com;25565|Example text`
![image](https://user-images.githubusercontent.com/5264946/90982580-e089c300-e55f-11ea-9ab8-38ee3fe65736.png)

This also causes the site to appear offline when using a known working port:
`nc;example.com;80`
`nc;.example.com;80|Example text`
![image](https://user-images.githubusercontent.com/5264946/90982599-0b741700-e560-11ea-90b1-f92bdfb8e45b.png)

From what I can tell the port is being recognised by the script but it isn't properly stripping custom text from the ports with nc. It appears the issue is the same with grep and traceroute.

**Comment by sengaya** [comment]
@Jakoski360 you need to append the `|` directly after the hostname (before the next `;`), not at the end. I guess that's not clear from the documentation as I provided only an example for `curl` where there are no more parameters after the hostname/url.

**Comment by Jakoski360** [comment]
@sengaya Thanks, that looks to have solved it.

Might be worth having a note in the documentation or `hostname_list` file for `nc` noting that custom text needs to be applied directly after the hostname, maybe something like below:

`nc;example.com|Example text;80`

**Comment by Cyclenerd** [comment]
I also changed my local installation and now use the new custom text function from @sengaya . I have also updated the help: https://github.com/Cyclenerd/static_status/commit/01ff3f3891d72bd84ce2d79093be70d791a4f4ac
