### ISSUE TITLE
Feature request: auto refresh code in html

### ISSUE THREAD

**Issue by somera** [Cyclenerd/static_status#22]
Configurable auto refresh will be a good feature:

in config:
`auto-refresh;5`

in html:
`<meta http-equiv=”refresh” content=”5" />`

**Comment by Cyclenerd** [comment]
Done: https://github.com/Cyclenerd/static_status/commit/5759c3a35ac9721ef66377f3efd2b5ddbe633103

**Comment by somera** [comment]
Thx. It worx fine!
