### ISSUE TITLE
Feature Request: Timezones

### ISSUE THREAD

**Issue by sennewood** [Cyclenerd/static_status#26]
It would be nice to be able to define a timezone, like "europe/berlin" or modify the UTC value, like "UTC+2".

**Comment by Cyclenerd** [comment]
Change `MY_DATE_TIME` or add `MY_DATE_TIME=$(date "+%d.%m.%Y %H:%M:%S")` without `-u` to your `config`.

**Comment by Cyclenerd** [comment]
I'll explain it better with https://github.com/Cyclenerd/static_status/commit/805806217eb8326952d526c8550ab43dbcfa1661. Thanks for the hint.
