### ISSUE TITLE
Question: How are "major outages" get triggerd?

### ISSUE THREAD

**Issue by sennewood** [Cyclenerd/static_status#27]
In the readme is a screenshot of a major outage, but how are those get triggered?

**Comment by moppman** [comment]
See https://github.com/Cyclenerd/static_status/blob/805806217eb8326952d526c8550ab43dbcfa1661/status.sh#L858
So a "major outage" is triggered if all the services you listed are affected.

**Comment by Cyclenerd** [comment]
To clarify: The message comes when more services are broken than healthy. Not everything has to be broken.

**Comment by sennewood** [comment]
How is "healthy" defined?

**Comment by Cyclenerd** [comment]
Not down `MY_HOSTNAME_STATUS_DOWN`.

**Comment by sennewood** [comment]
I meant in puncto: more broken than healthy. Is it >=51% broken?

**Comment by Cyclenerd** [comment]
It is greater-than not greater than or equal. @moppman posted the line `$MY_OUTAGE_COUNT" -gt "$MY_AVAILABLE_COUNT`. In other words: `if broken, down, outage > healthy, up, running then major outage`

Hope that explains your question.

**Comment by sennewood** [comment]
I was blind ... sorry ^^
Thank you both for the answer.
