### ISSUE TITLE
TODO: Resolv symlinks

### ISSUE THREAD

**Issue by sennewood** [Cyclenerd/static_status#28]
I saw this TODO in the code and thought a real issue is better - if not, close it :)

https://github.com/Cyclenerd/static_status/blob/805806217eb8326952d526c8550ab43dbcfa1661/status.sh#L94

**Comment by Cyclenerd** [comment]
I'm not even sure if that's important anymore?

**Comment by sennewood** [comment]
I guess not? ^^

**Comment by Cyclenerd** [comment]
✓ fixed https://github.com/Cyclenerd/static_status/commit/02de899f5aad34b5405bf6fe45925a08399ba92e
