### ISSUE TITLE
Question: Monitor DHCP (nc udp port)

### ISSUE THREAD

**Issue by plegrand1** [Cyclenerd/static_status#30]
Hello,
what should be the way to test udp port (dhcpd)

Thanks for your script and your answer
Pascal

**Comment by Cyclenerd** [comment]
With a custom script. The script could look like this...

dhcpd.sh
```
#!/bin/bash
if netcat -z -w 2 -v -u 192.168.100.1 67; then
        exit 0
else
        exit 9
fi
```

status_hostname_list.txt:
```
script;dhcpd.sh|DHCP
```

But if you want to be sure that DHCP really works, I recommend a more detailed test:
* Command: `sudo nmap --script broadcast-dhcp-discover`
* Nagios Plugin: <http://nagios-plugins.org/doc/man/check_dhcp.html>

**Comment by Cyclenerd** [comment]
I close this question
