### ISSUE TITLE
traceroute required if not used

### ISSUE THREAD

**Issue by kevinpapst** [Cyclenerd/static_status#31]
Fantastic tool that you provider here :heart: 
I tested so many status pages, yours matched > 90% of my expectations (and it looks good), thank you so much for sharing!

Now with that of my chest 😁 I wanted to post en enhancement for the future:
I am not using any `traceroute` test, but your script didn't wanted to start without installing it on my prod server.
Now this is easily solvable and lightweight, but not necessary. Adding an unused dependency into an automated infrastructure feels wrong.

Maybe you can add an error message upon the missing dependency ONLY if a trace route command is actually activated?

**Comment by Cyclenerd** [comment]
traceroute is now optional. Will now no longer be checked if the variable `MY_TRACEROUTE_HOST` is not set.

Add: `MY_TRACEROUTE_HOST=''` to your config.

**Comment by kevinpapst** [comment]
Cool, thank you for the quick response 👍
