### ISSUE TITLE
Status.svg

### ISSUE THREAD

**Issue by plegrand1** [Cyclenerd/static_status#34]
Just a litle question : 
How is the status.svg file used?
I can see that it is generated but I can't see when an d where it is used?

Thank you for your answer
Pascal

**Comment by Cyclenerd** [comment]
Do this help? https://github.com/Cyclenerd/static_status#svg-icon

**Comment by plegrand1** [comment]
Sorry, laziness probably, I did not read the whole readme.
Again sorry and thanks for the answer.
