### ISSUE TITLE
alert.sh not working with similar check names

### ISSUE THREAD

**Issue by brknkfr** [Cyclenerd/static_status#42]
I monitor to servers with `ping` and `ping6`. In `status_hostname_list.txt` I have:

```
ping;nameofserver.lan
ping6;nameofserver.lan.somethingmore
```
Assuming both servers are down and I'm doing an `alert.sh`, only one alert will work.

`MY_STATUS_CONFIG="/path/to/config" /usr/local/bin/alert.sh -c nameofserver.lan.somethingmore` -> WORKS
`MY_STATUS_CONFIG="/path/to/config" /usr/local/bin/alert.sh -c nameofserver.lan` -> WON'T WORK!

It can't work because the grep in the script gets _two_ values and not only _one_, because the grep in line 156 matches both checks (MY_CHECK variable).

**Comment by Cyclenerd** [comment]
Without your change (https://github.com/Cyclenerd/static_status/pull/43) it should be possible to search for `ping6;nameofserver.lan` and `ping;nameofserver.lan` as `MY_CHECK`. Also `nameofserver.lan.somethingmore;` should be possible. Have you tried that?

**Comment by brknkfr** [comment]
True, I didn't think about that. Thank you for the hint. I'll delete the PR.
