### ISSUE TITLE
Delay checks if one fails

### ISSUE THREAD

**Issue by kevinpapst** [Cyclenerd/static_status#48]
Hey @Cyclenerd ,

after running your awesome script for a couple of months, I am seeing the same issue coming up over and over again.
If there is some kind of outtake or just the slightest network hiccup, all checks will fail:

<img width="422" alt="Bildschirmfoto 2022-01-20 um 21 04 42" src="https://user-images.githubusercontent.com/533162/150413613-c2e12876-7b0f-4051-a41e-4f6eb8c0e41f.png">

Take this screenshot/event for example: I was using the site the entire time and there was definitely no downtime. But yeah, there might have been some kind of temporary network issue for a few seconds. 

What I would like to propose (and hit me if it is there and I just didn't find it): a configuration for either delayed checks, eg. wait 2 seconds between each test or at least a delay in case one test fails. This delay could be incremented for every other failing test.

What do you think? Is that a bad idea? Does anyone else see the issue as well?

**Comment by Cyclenerd** [comment]
You can use `MY_CURL_PARAMETERS` with `--retry` or increase `MY_MIN_DOWN_TIME`.

**Comment by kevinpapst** [comment]
Thanks for your feedback. I guess I need to update my script as I don't have the `MY_CURL_PARAMETERS` yet.

The only tests failing are `ping` and `grep` checks. Two other `script` tests are using `mysqladmin` internally and they are never failing. 

Anyways: you don't like the idea of a sleep() between the test in the for loop for adding some delay?

**Comment by Cyclenerd** [comment]
No, I don't think that's good. If curl or ping do not give the expected result (return code), something is definitely broken.

**Comment by kevinpapst** [comment]
Having delay in tests is common practice for various reasons. But this is your project. I will do it in my own fork then.

Thanks!
