### ISSUE TITLE
Feature Request: Downtime also in JSON output

### ISSUE THREAD

**Issue by Wilkware** [Cyclenerd/static_status#55]
Would it be possible to indicate the downtime for failed services in the JSON output as well?

**Comment by Cyclenerd** [comment]
Hi,

It is. Please see: https://github.com/Cyclenerd/static_status/blob/master/status.sh#L48
Example: https://cyclenerd.github.io/static_status/status.json

BR Nils

**Comment by Wilkware** [comment]
Sorry, I mean not only the state, also the time like in the html ...

![image](https://user-images.githubusercontent.com/24620975/233096002-951da3c7-e90a-433d-a87a-9b087f057e05.png)

Heiko

**Comment by Cyclenerd** [comment]
Thank you for clarification. Very good idea. I added it immediately: https://github.com/Cyclenerd/static_status/commit/11cf0f71639f412f8e6a8ad0ccbf6e4b1d11a474

BR Nils
