### ISSUE TITLE
CONTRIBUTING.md deserves an update!

### ISSUE THREAD

**Issue by HimanshuMahto** [Cyclenerd/static_status#59]
Maybe an update to CONTRIBUTING.md would be amazing.
Unlike other amazing repos, this repo's CONTRIBUTING.md looks plain and simple.

I think emojified, fun and precise version would be better!

Describe alternatives you've considered
An update would be amazing!

Additional context
If you are reading this, you are amazing! ⭐

Starred ⭐✔️

Thanks and regards,
Himanshu.

**Comment by Cyclenerd** [comment]
Pull request welcome 👍

**Comment by HimanshuMahto** [comment]
@Cyclenerd made a PR please do review it. #60

**Comment by Cyclenerd** [comment]
Super cool :) Thank you 👍

**Comment by HimanshuMahto** [comment]
Your most welcome 😄
