### ISSUE TITLE
Typo error in README.md

### ISSUE THREAD

**Issue by manavb2214** [Cyclenerd/static_status#70]
I found a typo in your provided text:

Instead of "Bagde" it should be "Badge".

So it should be corrected as:

[![Badge: GNU Bash](https://img.shields.io/badge/GNU%20Bash-4EAA25.svg?logo=gnubash&logoColor=white)](#readme)
[![Badge: ShellCheck](https://github.com/Cyclenerd/static_status/actions/workflows/shellcheck.yml/badge.svg?branch=master)](https://github.com/Cyclenerd/static_status/actions/workflows/shellcheck.yml)
[![Badge: Ubuntu 22.04 LTS](https://github.com/Cyclenerd/static_status/actions/workflows/ubuntu_2204.yml/badge.svg?branch=master)](https://github.com/Cyclenerd/static_status/actions/workflows/ubuntu_2204.yml)
[![Badge: GitHub](https://img.shields.io/github/license/cyclenerd/static_status)](https://github.com/Cyclenerd/static_status/blob/master/LICENSE)

**Comment by Cyclenerd** [comment]
Fixed. Thank you!

**Comment by manavb2214** [comment]
Thank you so much!!!
